spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: playground-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: db.playground.kafka.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size: 16384
      buffer-memory: 33554432
      acks: all
      compression-type: none
      properties:
        linger.ms: 5

playground:
  kafka:
    https:
      topic: playground.https-sessions
      session-count: 100
