[versions]
java = "21"
junit = "6.0.0"
springBoot = "4.1.1"
testcontainers = "2.0.5"
awaitility = "4.3.0"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
