plugins {
    alias(libs.plugins.spring.boot)
}

dependencies {
    implementation platform(libs.spring.boot.dependencies)
    implementation platform(libs.awssdk.bom)
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation libs.awssdk.dynamodb

    testImplementation platform(libs.spring.boot.dependencies)
    testImplementation platform(libs.testcontainers.bom)
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers-kafka'
    testImplementation libs.awaitility
}
