spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: playground-dynamo-streams
      properties:
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndFailExceptionHandler
    consumer:
      auto-offset-reset: earliest

playground:
  dynamo:
    https:
      topic: playground.https-sessions
      dynamo:
        region: us-east-1
        aggregate-table: https_session_aggregates
        event-table: https_session_events
